set_property IOSTANDARD LVCMOS33 [get_ports adc_rdy_a]
set_property IOSTANDARD LVCMOS33 [get_ports afe4400_rst_n_a]
set_property IOSTANDARD LVCMOS33 [get_ports afe_pdnz_a]
set_property IOSTANDARD LVCMOS33 [get_ports alm]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports dataReady]
set_property IOSTANDARD LVCMOS33 [get_ports dataReady_a]
set_property IOSTANDARD LVCMOS33 [get_ports diag_end_a]
set_property IOSTANDARD LVCMOS33 [get_ports diag_start]
set_property IOSTANDARD LVCMOS33 [get_ports led_add1]
set_property IOSTANDARD LVCMOS33 [get_ports led_add2]
set_property IOSTANDARD LVCMOS33 [get_ports led_sub1]
set_property IOSTANDARD LVCMOS33 [get_ports led_sub2]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sclk_a]
set_property IOSTANDARD LVCMOS33 [get_ports spisimo_a]
set_property IOSTANDARD LVCMOS33 [get_ports spisomi_a]
set_property IOSTANDARD LVCMOS33 [get_ports spiste_a]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property PACKAGE_PIN M20 [get_ports rst_n]
set_property PACKAGE_PIN M19 [get_ports diag_start]

set_property PACKAGE_PIN T14 [get_ports afe_pdnz_a]
set_property PACKAGE_PIN U12 [get_ports diag_end_a]
set_property PACKAGE_PIN U13 [get_ports sclk_a]
set_property PACKAGE_PIN V13 [get_ports spisomi_a]
set_property PACKAGE_PIN V15 [get_ports spisimo_a]
set_property PACKAGE_PIN T15 [get_ports spiste_a]
set_property PACKAGE_PIN R16 [get_ports adc_rdy_a]
set_property PACKAGE_PIN U17 [get_ports afe4400_rst_n_a]
set_property PACKAGE_PIN V17 [get_ports clk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]

set_property PACKAGE_PIN Y19 [get_ports uart_txd]
set_property PACKAGE_PIN D19 [get_ports led_add1]
set_property PACKAGE_PIN D20 [get_ports led_add2]
set_property PACKAGE_PIN L20 [get_ports led_sub1]
set_property PACKAGE_PIN L19 [get_ports led_sub2]
set_property PACKAGE_PIN R14 [get_ports alm]
set_property PACKAGE_PIN P14 [get_ports dataReady]

set_property PACKAGE_PIN N16 [get_ports dataReady_a]
